namespace App.Web.Components.Admin.Settings.Cotizacion;

/// <summary>Fake data used only by the Preview button in <see cref="CotizacionSettingsTab"/>.</summary>
public static class CotizacionTemplateSampleData
{
    public static object GetSampleData() => new
    {
        company_name = "Mantenimiento Demo S.A. de C.V.",
        company_direccion = "Av. Reforma 123, Col. Centro, Ciudad de México, 06000",
        mostrar_direccion = true,
        logo_base64 = string.Empty,
        has_logo = false,
        primary_color = "#1A6868",
        secondary_color = "#7B3FA0",
        cotizacion_id = 1,
        cotizacion_folio = "COT-2026-0001",
        fecha_generacion = DateTime.Now.ToString("dd/MM/yyyy"),
        hora_generacion = DateTime.Now.ToString("HH:mm"),
        cliente_nombre = "Juan Pérez",
        cliente_correo = "juan.perez@example.com",
        has_cliente_correo = true,
        cliente_telefono = "555-123-4567",
        has_cliente_telefono = true,
        cliente_direccion = "Calle Falsa 123, Col. Roma, Ciudad de México, 06700",
        has_cliente_direccion = true,
        cliente_tiene_datos_fiscales = true,
        cliente_razon_social = "Juan Pérez Servicios S.A. de C.V.",
        cliente_rfc = "PEPJ800101ABC",
        cliente_regimen_fiscal = "601 - General de Ley Personas Morales",
        subtotal = (15000m).ToString("C2"),
        incluir_iva = true,
        iva_tasa = (16m).ToString("F2"),
        iva_monto = (2400m).ToString("C2"),
        total = (17400m).ToString("C2"),
        has_payment_terms = true,
        payment_terms_text = "50% de anticipo para iniciar los trabajos, 50% restante contra entrega.",
        mostrar_datos_bancarios = true,
        banco_beneficiario = "Mantenimiento Demo S.A. de C.V.",
        banco_rfc = "MDE010101XYZ",
        banco_nombre = "BBVA",
        banco_numero_cuenta = "0123456789",
        banco_clabe = "012180001234567895",
        banco_swift = "BCMRMXMM",
        mostrar_contacto = true,
        contacto_sitio_web = "www.mantenimientodemo.com",
        has_contacto_sitio_web = true,
        contacto_telefono = "555-000-1111",
        has_contacto_telefono = true,
        contacto_correo = "contacto@mantenimientodemo.com",
        has_contacto_correo = true,
        contacto_whatsapp = "555-222-3333",
        has_contacto_whatsapp = true,
        contacto_facebook = "MantenimientoDemo",
        has_contacto_facebook = true,
        contacto_instagram = "@mantenimientodemo",
        has_contacto_instagram = true,
        label_quotation = "Cotización",
        label_client = "Cliente",
        label_fiscal_data = "Datos Fiscales",
        label_date = "Fecha",
        label_email = "Correo",
        label_phone = "Teléfono",
        label_address = "Dirección",
        label_rfc = "RFC",
        label_tax_regime = "Régimen Fiscal",
        label_service = "Servicio",
        label_quantity = "Cantidad",
        label_unit_price = "Precio Unitario",
        label_subtotal = "Subtotal",
        label_iva = "IVA",
        label_total = "Total",
        label_payment_terms = "Términos de Pago",
        label_bank_transfer = "Datos para Transferencia",
        label_beneficiary = "Beneficiario",
        label_bank = "Banco",
        label_account_number = "Número de Cuenta",
        label_clabe = "CLABE",
        label_swift = "SWIFT/BIC",
        lineas = new[]
        {
            new
            {
                indice = 1,
                servicio_nombre = "Impermeabilizante",
                unidad_medida = "Metro Cuadrado",
                cantidad = (150m).ToString("F2"),
                precio_unitario = (60m).ToString("C2"),
                subtotal = (9000m).ToString("C2")
            },
            new
            {
                indice = 2,
                servicio_nombre = "Pintura",
                unidad_medida = "Metro Cuadrado",
                cantidad = (200m).ToString("F2"),
                precio_unitario = (30m).ToString("C2"),
                subtotal = (6000m).ToString("C2")
            }
        }
    };
}
