namespace App.Core.Utils;

/// <summary>
/// Parses barcode strings generated by BarcodeGeneratorService.
/// Internal bulk format: {ProductId}-{QuantityMillis:D6}-{PriceCents}
/// Example: 156-020000-72414  →  productId=156, qty=20.000, price=$724.14
/// </summary>
public static class BarcodeParser
{
    /// <summary>
    /// Tries to parse a bulk product barcode. Returns true if the string matches the
    /// internal format {ProductId}-{QtyMillis}-{PriceCents}.
    /// </summary>
    public static bool TryParseBulkBarcode(
        string text,
        out long productId,
        out decimal quantity,
        out decimal totalPrice)
    {
        productId = 0;
        quantity = 0;
        totalPrice = 0;

        if (string.IsNullOrWhiteSpace(text)) return false;

        var lastDash = text.LastIndexOf('-');
        if (lastDash < 1) return false;
        var secondDash = text.LastIndexOf('-', lastDash - 1);
        if (secondDash < 0) return false;

        if (!long.TryParse(text[..secondDash], out productId)) return false;
        if (!long.TryParse(text.Substring(secondDash + 1, lastDash - secondDash - 1), out var qtyMillis)) return false;
        if (!long.TryParse(text[(lastDash + 1)..], out var priceCents)) return false;

        quantity = qtyMillis / 1000m;
        totalPrice = priceCents / 100m;
        return true;
    }

    /// <summary>
    /// Returns true if the string looks like a standard product barcode
    /// (EAN-8, EAN-13, UPC-A, etc.) — 8 or more consecutive digits.
    /// </summary>
    public static bool IsLikelyStandardBarcode(string text) =>
        !string.IsNullOrWhiteSpace(text) && text.Length >= 8 && text.All(char.IsDigit);
}
