using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

using App.Core.Base;

namespace App.Models.Shop;

[Table("sh_physical_inventory_counts")]
public class PhysicalInventoryCount : BaseEntity<long>
{
    [Required]
    [StringLength(20)]
    public string BatchNumber { get; set; } = null!;

    /// <summary>
    /// Groups the InventoryMovement records generated by this count
    /// </summary>
    public Guid BatchId { get; set; }

    public int LocationId { get; set; }

    [StringLength(50)]
    public string? Reference { get; set; }

    [Required]
    [StringLength(500)]
    public string Reason { get; set; } = null!;

    public DateTime CountDate { get; set; }

    [ForeignKey(nameof(LocationId))]
    public virtual Location Location { get; set; } = null!;

    public virtual ICollection<PhysicalInventoryCountLine> Lines { get; set; } = [];
}
