-- ============================================================
-- Cleeny - Create / Reset Super Admin User
-- ============================================================
-- Creates or resets the SuperAdmin user with all claims.
-- If the user already exists, resets the password and
-- re-syncs all claims. Safe to run multiple times.
--
-- BEFORE RUNNING — generate a password hash:
--
--   python3 tools/db/generate-password-hash.py "Admin@1234!"
--
--   Copy the output and paste it as the value of @passwordHash below.
--
-- HOW TO USE:
--   1. Generate the hash:
--        python3 tools/db/generate-password-hash.py "MiContraseña@123"
--   2. Set @passwordHash, @username, @email, @fullName below.
--   3. Run this script:
--        docker exec -i <container> mysql -uroot -p<password> App < tools/db/create-superadmin.sql
--      or paste it directly in your MySQL client.
--
-- Does NOT touch: products, sales, inventory, or any other data.
-- ============================================================


-- ============================================================
-- CONFIGURATION — edit these values
-- ============================================================
USE `App`;

SET @username     = 'admin2';
SET @email        = 'admin2@cleeny.local';
SET @fullName     = 'Super Admin2';

-- Paste the hash generated by the python3 command above:
SET @passwordHash = 'AQAAAAEAAYagAAAAEN1T+3iTo5hXYHwjceMl1xw4rDX4BocrA5VUwWFFne13uXNMLDVbDZhnPK0wMGNYMg==';

-- ============================================================
-- VALIDATION
-- ============================================================
SELECT IF(
    @passwordHash = 'PASTE_GENERATED_HASH_HERE',
    CONCAT('\n\nERROR: You must generate and set @passwordHash first.\n',
           'See the instructions at the top of this file.\n\n'),
    'Hash OK — proceeding...'
) AS check_hash;

-- Abort if hash was not replaced (works in strict mode via signal)
-- Remove the SELECT above and uncomment the block below if you want a hard stop:
-- SET @abort = IF(@passwordHash = 'PASTE_GENERATED_HASH_HERE',
--     (SELECT 1 FROM information_schema.tables WHERE 1 = 0), NULL);


-- ============================================================
-- PRE-CHECK
-- ============================================================
SELECT 'AspNetUsers'      AS tbl, COUNT(*) AS cnt FROM AspNetUsers   WHERE UserName = @username;
SELECT 'AspNetUserClaims' AS tbl, COUNT(*) AS cnt FROM AspNetUserClaims
  WHERE UserId = (SELECT Id FROM AspNetUsers WHERE UserName = @username LIMIT 1);


-- ============================================================
-- START TRANSACTION
-- ============================================================
START TRANSACTION;

-- ── 1. SuperAdmin role ──────────────────────────────────────
INSERT INTO AspNetRoles (Id, Name, NormalizedName, ConcurrencyStamp)
VALUES (UUID(), 'SuperAdmin', 'SUPERADMIN', UUID())
ON DUPLICATE KEY UPDATE Name = Name;

SET @roleId = (SELECT Id FROM AspNetRoles WHERE NormalizedName = 'SUPERADMIN' LIMIT 1);

-- ── 2. Upsert user ──────────────────────────────────────────
SET @existingId = (SELECT Id FROM AspNetUsers WHERE UserName = @username LIMIT 1);
SET @newId      = UUID();

-- Create if not exists
INSERT INTO AspNetUsers (
    Id, UserName, NormalizedUserName, Email, NormalizedEmail,
    EmailConfirmed, PasswordHash, SecurityStamp, ConcurrencyStamp,
    PhoneNumber, PhoneNumberConfirmed, TwoFactorEnabled,
    LockoutEnd, LockoutEnabled, AccessFailedCount,
    FullName, IsActive, LastLogin,
    CreatedBy, CreatedAt, ModifiedBy, ModifiedAt, IsDeleted
)
SELECT
    @newId,
    @username, UPPER(@username),
    @email, UPPER(@email),
    1,
    @passwordHash,
    UPPER(REPLACE(UUID(), '-', '')),
    UUID(),
    NULL, 0, 0,
    NULL, 1, 0,
    @fullName, 1, NULL,
    'Script', UTC_TIMESTAMP(), 'Script', UTC_TIMESTAMP(), 0
WHERE @existingId IS NULL;

-- Reset if already exists
UPDATE AspNetUsers
SET PasswordHash      = @passwordHash,
    SecurityStamp     = UPPER(REPLACE(UUID(), '-', '')),
    NormalizedEmail   = UPPER(@email),
    Email             = @email,
    EmailConfirmed    = 1,
    IsActive          = 1,
    LockoutEnd        = NULL,
    AccessFailedCount = 0,
    ModifiedBy        = 'Script',
    ModifiedAt        = UTC_TIMESTAMP()
WHERE UserName = @username;

SET @userId = (SELECT Id FROM AspNetUsers WHERE UserName = @username LIMIT 1);

-- ── 3. Role assignment ──────────────────────────────────────
INSERT IGNORE INTO AspNetUserRoles (UserId, RoleId)
VALUES (@userId, @roleId);

-- ── 4. Claims — full ApplicationClaims sync ─────────────────
DELETE FROM AspNetUserClaims WHERE UserId = @userId;

INSERT INTO AspNetUserClaims (UserId, ClaimType, ClaimValue) VALUES
  -- Shop
  (@userId, 'Shop.Access',                        'Shop.Access'),
  (@userId, 'Shop.Inventory.View',                'Shop.Inventory.View'),
  (@userId, 'Shop.Inventory.Manage',              'Shop.Inventory.Manage'),
  (@userId, 'Shop.Inventory.Export',              'Shop.Inventory.Export'),
  (@userId, 'Shop.InventoryHistory.View',         'Shop.InventoryHistory.View'),
  (@userId, 'Shop.InventoryTransfers.View',       'Shop.InventoryTransfers.View'),
  (@userId, 'Shop.InventoryTransfers.Manage',     'Shop.InventoryTransfers.Manage'),
  (@userId, 'Shop.InventoryInputs.View',          'Shop.InventoryInputs.View'),
  (@userId, 'Shop.InventoryInputs.Manage',        'Shop.InventoryInputs.Manage'),
  (@userId, 'Shop.InventoryAdjustments.View',     'Shop.InventoryAdjustments.View'),
  (@userId, 'Shop.InventoryAdjustments.Manage',   'Shop.InventoryAdjustments.Manage'),
  (@userId, 'Shop.InventoryAlerts.View',          'Shop.InventoryAlerts.View'),
  (@userId, 'Shop.InventoryAlerts.ReceiveEmails', 'Shop.InventoryAlerts.ReceiveEmails'),
  (@userId, 'Shop.Products.View',                 'Shop.Products.View'),
  (@userId, 'Shop.Products.Manage',               'Shop.Products.Manage'),
  (@userId, 'Shop.Products.Delete',               'Shop.Products.Delete'),
  (@userId, 'Shop.Products.BulkImport',           'Shop.Products.BulkImport'),
  (@userId, 'Shop.Prices.View',                   'Shop.Prices.View'),
  (@userId, 'Shop.Prices.Manage',                 'Shop.Prices.Manage'),
  (@userId, 'Shop.Discounts.Manage',              'Shop.Discounts.Manage'),
  (@userId, 'Shop.Discounts.Authorize',           'Shop.Discounts.Authorize'),
  (@userId, 'Shop.Sales.View',                    'Shop.Sales.View'),
  (@userId, 'Shop.Sales.ViewHistory',             'Shop.Sales.ViewHistory'),
  (@userId, 'Shop.Sales.Create',                  'Shop.Sales.Create'),
  (@userId, 'Shop.Sales.Cancel',                  'Shop.Sales.Cancel'),
  (@userId, 'Shop.Sales.ViewReports',             'Shop.Sales.ViewReports'),
  (@userId, 'Shop.Sales.ViewDailySummary',        'Shop.Sales.ViewDailySummary'),
  (@userId, 'Shop.Sales.ExportDailySummary',      'Shop.Sales.ExportDailySummary'),
  (@userId, 'Shop.Invoice.Create',                'Shop.Invoice.Create'),
  (@userId, 'Shop.Invoice.View',                  'Shop.Invoice.View'),
  (@userId, 'Shop.Invoice.Cancel',                'Shop.Invoice.Cancel'),
  (@userId, 'Shop.StampBalance.View',             'Shop.StampBalance.View'),
  (@userId, 'Shop.StampBalance.ReceiveAlerts',    'Shop.StampBalance.ReceiveAlerts'),
  (@userId, 'Shop.Warehouses.View',               'Shop.Warehouses.View'),
  (@userId, 'Shop.Warehouses.Manage',             'Shop.Warehouses.Manage'),
  (@userId, 'Shop.Warehouses.Delete',             'Shop.Warehouses.Delete'),
  (@userId, 'Shop.Quotations.View',               'Shop.Quotations.View'),
  (@userId, 'Shop.Quotations.Create',             'Shop.Quotations.Create'),
  (@userId, 'Shop.Quotations.Edit',               'Shop.Quotations.Edit'),
  (@userId, 'Shop.Quotations.Delete',             'Shop.Quotations.Delete'),
  (@userId, 'Shop.Quotations.Send',               'Shop.Quotations.Send'),
  (@userId, 'Shop.Quotations.ConvertToRemission', 'Shop.Quotations.ConvertToRemission'),
  (@userId, 'Shop.Quotations.ConvertToSale',      'Shop.Quotations.ConvertToSale'),
  (@userId, 'Shop.Remissions.View',               'Shop.Remissions.View'),
  (@userId, 'Shop.Remissions.Create',             'Shop.Remissions.Create'),
  (@userId, 'Shop.Remissions.Cancel',             'Shop.Remissions.Cancel'),
  (@userId, 'Shop.Remissions.Consolidate',        'Shop.Remissions.Consolidate'),
  (@userId, 'Shop.CashRegister.View',             'Shop.CashRegister.View'),
  (@userId, 'Shop.CashRegister.Manage',           'Shop.CashRegister.Manage'),
  (@userId, 'Shop.CashRegister.Withdraw',         'Shop.CashRegister.Withdraw'),
  (@userId, 'Shop.CashRegister.ViewHistory',      'Shop.CashRegister.ViewHistory'),
  (@userId, 'Shop.CashRegister.ViewReport',       'Shop.CashRegister.ViewReport'),
  -- Admin
  (@userId, 'Admin.Access',                       'Admin.Access'),
  (@userId, 'Admin.Users.View',                   'Admin.Users.View'),
  (@userId, 'Admin.Users.Manage',                 'Admin.Users.Manage'),
  (@userId, 'Admin.Users.Delete',                 'Admin.Users.Delete'),
  (@userId, 'Admin.Users.ResetPassword',          'Admin.Users.ResetPassword'),
  (@userId, 'Admin.Roles.View',                   'Admin.Roles.View'),
  (@userId, 'Admin.Roles.Manage',                 'Admin.Roles.Manage'),
  (@userId, 'Admin.Roles.Delete',                 'Admin.Roles.Delete'),
  (@userId, 'Admin.Settings.View',                'Admin.Settings.View'),
  (@userId, 'Admin.Settings.Manage',              'Admin.Settings.Manage'),
  (@userId, 'Admin.FiscalSettings.View',          'Admin.FiscalSettings.View'),
  (@userId, 'Admin.FiscalSettings.Manage',        'Admin.FiscalSettings.Manage'),
  (@userId, 'Admin.BillingSettings.View',         'Admin.BillingSettings.View'),
  (@userId, 'Admin.BillingSettings.Manage',       'Admin.BillingSettings.Manage'),
  (@userId, 'Admin.WarehouseSettings.View',       'Admin.WarehouseSettings.View'),
  (@userId, 'Admin.WarehouseSettings.Manage',     'Admin.WarehouseSettings.Manage'),
  (@userId, 'Admin.BranchSettings.View',          'Admin.BranchSettings.View'),
  (@userId, 'Admin.BranchSettings.Manage',        'Admin.BranchSettings.Manage'),
  (@userId, 'Admin.EmailSettings.View',           'Admin.EmailSettings.View'),
  (@userId, 'Admin.EmailSettings.Manage',         'Admin.EmailSettings.Manage'),
  (@userId, 'Admin.TaxRates.View',                'Admin.TaxRates.View'),
  (@userId, 'Admin.TaxRates.Manage',              'Admin.TaxRates.Manage'),
  (@userId, 'Admin.TaxRates.Delete',              'Admin.TaxRates.Delete'),
  (@userId, 'Admin.UnitMeasures.View',            'Admin.UnitMeasures.View'),
  (@userId, 'Admin.UnitMeasures.Manage',          'Admin.UnitMeasures.Manage'),
  (@userId, 'Admin.InitialSetup.Manage',          'Admin.InitialSetup.Manage'),
  (@userId, 'Admin.Audit.View',                   'Admin.Audit.View'),
  (@userId, 'Admin.Audit.ViewReports',            'Admin.Audit.ViewReports'),
  (@userId, 'Admin.Permissions.View',             'Admin.Permissions.View'),
  (@userId, 'Admin.Permissions.Manage',           'Admin.Permissions.Manage'),
  (@userId, 'Admin.Disccounts.View',              'Admin.Disccounts.View'),
  (@userId, 'Admin.Disccounts.Manage',            'Admin.Disccounts.Manage'),
  (@userId, 'Admin.TicketSettings.View',          'Admin.TicketSettings.View'),
  (@userId, 'Admin.TicketSettings.Manage',        'Admin.TicketSettings.Manage'),
  (@userId, 'Admin.Cashiers.View',                'Admin.Cashiers.View'),
  (@userId, 'Admin.Cashiers.Manage',              'Admin.Cashiers.Manage'),
  (@userId, 'Admin.CashStations.View',            'Admin.CashStations.View'),
  (@userId, 'Admin.CashStations.Manage',          'Admin.CashStations.Manage'),
  -- Shared
  (@userId, 'Shared.Access',                      'Shared.Access'),
  (@userId, 'Shared.Customers.View',              'Shared.Customers.View'),
  (@userId, 'Shared.Customers.Manage',            'Shared.Customers.Manage'),
  (@userId, 'Shared.Customers.Delete',            'Shared.Customers.Delete'),
  (@userId, 'Shared.Suppliers.View',              'Shared.Suppliers.View'),
  (@userId, 'Shared.Suppliers.Manage',            'Shared.Suppliers.Manage'),
  (@userId, 'Shared.Suppliers.Delete',            'Shared.Suppliers.Delete'),
  (@userId, 'Shared.Dashboard.View',              'Shared.Dashboard.View'),
  (@userId, 'Shared.Reports.View',                'Shared.Reports.View'),
  (@userId, 'Shared.Reports.Generate',            'Shared.Reports.Generate'),
  -- Labels
  (@userId, 'Labels.Access',                      'Labels.Access'),
  (@userId, 'Labels.View',                        'Labels.View'),
  (@userId, 'Labels.Print',                       'Labels.Print');


-- ============================================================
-- POST-CHECK
-- ============================================================
SELECT
  u.UserName,
  u.Email,
  u.FullName,
  u.IsActive,
  r.Name          AS Role,
  COUNT(c.Id)     AS Claims
FROM AspNetUsers u
JOIN AspNetUserRoles ur  ON ur.UserId = u.Id
JOIN AspNetRoles r       ON r.Id      = ur.RoleId
LEFT JOIN AspNetUserClaims c ON c.UserId = u.Id
WHERE u.UserName = @username
GROUP BY u.Id, r.Name;


-- ============================================================
-- When ready: review post-check above, then COMMIT.
-- If anything looks wrong: ROLLBACK instead.
-- ============================================================
-- ROLLBACK;
COMMIT;
