-- ============================================================
-- AppBase - Create / Reset Super Admin User
-- ============================================================
-- Creates or resets the SuperAdmin user with all claims.
-- If the user already exists, resets the password and
-- re-syncs all claims. Safe to run multiple times.
--
-- BEFORE RUNNING — generate a password hash:
--
--   python3 tools/db/generate-password-hash.py "Admin@1234!"
--
--   Copy the output and paste it as the value of @passwordHash below.
--
-- HOW TO USE:
--   1. Generate the hash:
--        python3 tools/db/generate-password-hash.py "MiContraseña@123"
--   2. Set @passwordHash, @username, @email, @fullName below.
--   3. Run this script:
--        docker exec -i <container> mysql -uroot -p<password> App < tools/db/create-superadmin.sql
--      or paste it directly in your MySQL client.
-- ============================================================


-- ============================================================
-- CONFIGURATION — edit these values
-- ============================================================
USE `App`;

SET @username     = 'admin2';
SET @email        = 'admin2@example.com';
SET @fullName     = 'Super Admin2';

-- Paste the hash generated by the python3 command above:
SET @passwordHash = 'PASTE_GENERATED_HASH_HERE';

-- ============================================================
-- VALIDATION
-- ============================================================
SELECT IF(
    @passwordHash = 'PASTE_GENERATED_HASH_HERE',
    CONCAT('\n\nERROR: You must generate and set @passwordHash first.\n',
           'See the instructions at the top of this file.\n\n'),
    'Hash OK — proceeding...'
) AS check_hash;


-- ============================================================
-- PRE-CHECK
-- ============================================================
SELECT 'AspNetUsers'      AS tbl, COUNT(*) AS cnt FROM AspNetUsers   WHERE UserName = @username;
SELECT 'AspNetUserClaims' AS tbl, COUNT(*) AS cnt FROM AspNetUserClaims
  WHERE UserId = (SELECT Id FROM AspNetUsers WHERE UserName = @username LIMIT 1);


-- ============================================================
-- START TRANSACTION
-- ============================================================
START TRANSACTION;

-- ── 1. SuperAdmin role ──────────────────────────────────────
INSERT INTO AspNetRoles (Id, Name, NormalizedName, ConcurrencyStamp)
VALUES (UUID(), 'SuperAdmin', 'SUPERADMIN', UUID())
ON DUPLICATE KEY UPDATE Name = Name;

SET @roleId = (SELECT Id FROM AspNetRoles WHERE NormalizedName = 'SUPERADMIN' LIMIT 1);

-- ── 2. Upsert user ──────────────────────────────────────────
SET @existingId = (SELECT Id FROM AspNetUsers WHERE UserName = @username LIMIT 1);
SET @newId      = UUID();

-- Create if not exists
INSERT INTO AspNetUsers (
    Id, UserName, NormalizedUserName, Email, NormalizedEmail,
    EmailConfirmed, PasswordHash, SecurityStamp, ConcurrencyStamp,
    PhoneNumber, PhoneNumberConfirmed, TwoFactorEnabled,
    LockoutEnd, LockoutEnabled, AccessFailedCount,
    FullName, IsActive, LastLogin,
    CreatedBy, CreatedAt, ModifiedBy, ModifiedAt, IsDeleted
)
SELECT
    @newId,
    @username, UPPER(@username),
    @email, UPPER(@email),
    1,
    @passwordHash,
    UPPER(REPLACE(UUID(), '-', '')),
    UUID(),
    NULL, 0, 0,
    NULL, 1, 0,
    @fullName, 1, NULL,
    'Script', UTC_TIMESTAMP(), 'Script', UTC_TIMESTAMP(), 0
WHERE @existingId IS NULL;

-- Reset if already exists
UPDATE AspNetUsers
SET PasswordHash      = @passwordHash,
    SecurityStamp     = UPPER(REPLACE(UUID(), '-', '')),
    NormalizedEmail   = UPPER(@email),
    Email             = @email,
    EmailConfirmed    = 1,
    IsActive          = 1,
    LockoutEnd        = NULL,
    AccessFailedCount = 0,
    ModifiedBy        = 'Script',
    ModifiedAt        = UTC_TIMESTAMP()
WHERE UserName = @username;

SET @userId = (SELECT Id FROM AspNetUsers WHERE UserName = @username LIMIT 1);

-- ── 3. Role assignment ──────────────────────────────────────
INSERT IGNORE INTO AspNetUserRoles (UserId, RoleId)
VALUES (@userId, @roleId);

-- ── 4. Claims — full ApplicationClaims sync ─────────────────
DELETE FROM AspNetUserClaims WHERE UserId = @userId;

INSERT INTO AspNetUserClaims (UserId, ClaimType, ClaimValue) VALUES
  -- Admin
  (@userId, 'Admin.Access',                       'Admin.Access'),
  (@userId, 'Admin.Users.View',                   'Admin.Users.View'),
  (@userId, 'Admin.Users.Manage',                 'Admin.Users.Manage'),
  (@userId, 'Admin.Users.Delete',                 'Admin.Users.Delete'),
  (@userId, 'Admin.Users.ResetPassword',          'Admin.Users.ResetPassword'),
  (@userId, 'Admin.Roles.View',                   'Admin.Roles.View'),
  (@userId, 'Admin.Roles.Manage',                 'Admin.Roles.Manage'),
  (@userId, 'Admin.Roles.Delete',                 'Admin.Roles.Delete'),
  (@userId, 'Admin.Settings.View',                'Admin.Settings.View'),
  (@userId, 'Admin.Settings.Manage',              'Admin.Settings.Manage'),
  (@userId, 'Admin.EmailSettings.View',           'Admin.EmailSettings.View'),
  (@userId, 'Admin.EmailSettings.Manage',         'Admin.EmailSettings.Manage'),
  (@userId, 'Admin.Audit.View',                   'Admin.Audit.View'),
  (@userId, 'Admin.Permissions.View',             'Admin.Permissions.View'),
  (@userId, 'Admin.Permissions.Manage',           'Admin.Permissions.Manage'),
  -- Shared
  (@userId, 'Shared.Access',                      'Shared.Access'),
  (@userId, 'Shared.Dashboard.View',              'Shared.Dashboard.View');


-- ============================================================
-- POST-CHECK
-- ============================================================
SELECT
  u.UserName,
  u.Email,
  u.FullName,
  u.IsActive,
  r.Name          AS Role,
  COUNT(c.Id)     AS Claims
FROM AspNetUsers u
JOIN AspNetUserRoles ur  ON ur.UserId = u.Id
JOIN AspNetRoles r       ON r.Id      = ur.RoleId
LEFT JOIN AspNetUserClaims c ON c.UserId = u.Id
WHERE u.UserName = @username
GROUP BY u.Id, r.Name;


-- ============================================================
-- When ready: review post-check above, then COMMIT.
-- If anything looks wrong: ROLLBACK instead.
-- ============================================================
-- ROLLBACK;
COMMIT;
