-- ============================================================
-- Cleeny - Sales Reset Script
-- ============================================================
-- Deletes all sales and directly related data:
--   invoices, payments, sale details, inventory movements
--   from sales, cash registers and cash register movements.
--
-- HOW TO USE:
--   1. Run as-is -> ends with ROLLBACK, no real changes.
--      Check pre/post counts in output.
--   2. When ready: comment ROLLBACK, uncomment COMMIT. Re-run.
--
-- WARNING: Irreversible once committed. Take a backup first.
--
-- Does NOT delete: products, customers, locations, suppliers,
--   stock entries, adjustment entries, or non-SALE inventory
--   movements. Inventory quantities are NOT automatically
--   recalculated — reset sh_inventory manually if needed.
-- ============================================================


-- ============================================================
-- PRE-CHECK (outside transaction)
-- ============================================================
USE App;
SELECT 'sh_sales'                      AS tbl, COUNT(*) AS cnt FROM sh_sales;
SELECT 'sh_sale_details'               AS tbl, COUNT(*) AS cnt FROM sh_sale_details;
SELECT 'sh_sale_payments'              AS tbl, COUNT(*) AS cnt FROM sh_sale_payments;
SELECT 'mx_invoices'                   AS tbl, COUNT(*) AS cnt FROM mx_invoices;
SELECT 'mx_invoice_files'              AS tbl, COUNT(*) AS cnt FROM mx_invoice_files;
SELECT 'sh_inventory_movements (SALE)' AS tbl, COUNT(*) AS cnt FROM sh_inventory_movements WHERE MovementType = 'SALE';
SELECT 'sh_cash_registers'             AS tbl, COUNT(*) AS cnt FROM sh_cash_registers;
SELECT 'sh_cash_register_movements'    AS tbl, COUNT(*) AS cnt FROM sh_cash_register_movements;
SELECT 'sh_cash_register_denominations'AS tbl, COUNT(*) AS cnt FROM sh_cash_register_denominations;


-- ============================================================
-- DELETION (wrapped in transaction)
-- ============================================================
BEGIN;

-- 1. CFDI invoice files (cascade child of mx_invoices)
DELETE FROM mx_invoice_files;

-- 2. CFDI invoices (FK Restrict -> sh_sales, must go before sales)
DELETE FROM mx_invoices;

-- 3. Inventory movements generated by sales
DELETE FROM sh_inventory_movements WHERE MovementType = 'SALE';

-- 4. Sales (cascades to sh_sale_details and sh_sale_payments)
DELETE FROM sh_sales;

-- 5. Cash register closing denominations
DELETE FROM sh_cash_register_denominations;

-- 6. Cash register movements (withdrawals, deposits, etc.)
DELETE FROM sh_cash_register_movements;

-- 7. Cash registers (sessions)
DELETE FROM sh_cash_registers;

-- Optional: reset auto-increment counters (uncomment if needed)
ALTER TABLE sh_sales                       AUTO_INCREMENT = 1;
ALTER TABLE sh_sale_details                AUTO_INCREMENT = 1;
ALTER TABLE sh_sale_payments               AUTO_INCREMENT = 1;
ALTER TABLE mx_invoices                    AUTO_INCREMENT = 1;
ALTER TABLE mx_invoice_files               AUTO_INCREMENT = 1;
ALTER TABLE sh_inventory_movements         AUTO_INCREMENT = 1;
ALTER TABLE sh_cash_registers              AUTO_INCREMENT = 1;
ALTER TABLE sh_cash_register_movements     AUTO_INCREMENT = 1;
ALTER TABLE sh_cash_register_denominations AUTO_INCREMENT = 1;

-- ROLLBACK;   -- <- no changes saved (safe default)
COMMIT;  -- <- uncomment to apply permanently


-- ============================================================
-- POST-CHECK (outside transaction)
-- ============================================================
SELECT 'sh_sales'                      AS tbl, COUNT(*) AS cnt FROM sh_sales;
SELECT 'sh_sale_details'               AS tbl, COUNT(*) AS cnt FROM sh_sale_details;
SELECT 'sh_sale_payments'              AS tbl, COUNT(*) AS cnt FROM sh_sale_payments;
SELECT 'mx_invoices'                   AS tbl, COUNT(*) AS cnt FROM mx_invoices;
SELECT 'mx_invoice_files'              AS tbl, COUNT(*) AS cnt FROM mx_invoice_files;
SELECT 'sh_inventory_movements (SALE)' AS tbl, COUNT(*) AS cnt FROM sh_inventory_movements WHERE MovementType = 'SALE';
SELECT 'sh_cash_registers'             AS tbl, COUNT(*) AS cnt FROM sh_cash_registers;
SELECT 'sh_cash_register_movements'    AS tbl, COUNT(*) AS cnt FROM sh_cash_register_movements;
SELECT 'sh_cash_register_denominations'AS tbl, COUNT(*) AS cnt FROM sh_cash_register_denominations;
