<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\App.Core\App.Core.csproj" />
    <ProjectReference Include="..\App.Models\App.Models.csproj" />
    <ProjectReference Include="..\App.Models.Data\App.Models.Data.csproj" />
    <ProjectReference Include="..\App.Shared\App.Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Resources\EmailTemplates\**\*.html" />
    <EmbeddedResource Include="Resources\EmailTemplates\**\*.css" />
    <EmbeddedResource Include="Resources\PdfTemplates\**\*.html" />
    <EmbeddedResource Include="Resources\PdfTemplates\**\*.css" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Resources\Xslt\cadenaoriginal_4_0.xslt" />
    <EmbeddedResource Include="Resources\Xslt\SAT\**\*.xslt" />
    <EmbeddedResource Include="Resources\Xsd\cfdv40.xsd" />
    <EmbeddedResource Include="Resources\Xsd\tdCFDI.xsd" />
    <EmbeddedResource Include="Resources\Xsd\catCFDI.xsd" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="12.0.1" />
    <PackageReference Include="CsvHelper" Version="33.1.0" />
    <PackageReference Include="EPPlus" Version="7.7.3" />
    <PackageReference Include="MailKit" Version="4.16.0" />
    <PackageReference Include="Microsoft.Extensions.Localization" Version="9.0.12" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="9.0.12" />
    <PackageReference Include="Microsoft.Extensions.Options" Version="9.0.12" />
    <PackageReference Include="PuppeteerSharp" Version="20.2.5" />
    <PackageReference Include="BouncyCastle.Cryptography" Version="2.6.2" />
    <PackageReference Include="QRCoder" Version="1.7.0" />
    <PackageReference Include="Razor.Templating.Core" Version="2.1.0" />
    <PackageReference Include="Scriban" Version="7.1.0" />
    <PackageReference Include="SixLabors.ImageSharp" Version="3.1.12" />
    <PackageReference Include="ZXing.Net" Version="0.16.9" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
